### ISSUE TITLE
This project needs severe updating and fixing.

### ISSUE THREAD

**Issue by ghost** [zhtengw/deepin-overlay#137]
Hello i would like to say that this overlay has not been updated since march 2021 or so and i would like to say that it needs severe fixing after a ton of stuff i encountered.

The first thing i encountered During installing dde-meta was dev-qt/qtxcb-private-headers EAPI not being compatible by default and you can fix it although with some messing around.

After that for the most part it installed fine but when it came to the deepin parts of the DE it just failed to compile without obvious reasons for example deepin-draw worked fine from source but from these ebuilds it just failed and certain things like dde-daemon were just failing and after hours of messing around i got a desktop with a mouse and than crashed back to the display manager.

Overall expierence:
Terrrible and not worth it as of right now.

**Comment by blacklightpy** [comment]
> Hello i would like to say that this overlay has not been updated since march 2021 or so and i would like to say that it needs severe fixing after a ton of stuff i encountered.

Hello ghost person, I think you should be looking here: https://github.com/deepin-community/deepin-overlay/tree/fix-build
It's the same, but updated upto Dec 2022, and has fixed the build. But it removes deepin-wine due because it's a proprietary blob.

Edit: just realized ghosts are deleted accounts, still this may help anyone else.
