### ISSUE TITLE
emerge: there are no ebuilds to satisfy "app-admin/system-config-printer-gnome".

### ISSUE THREAD

**Issue by psykotik1** [zhtengw/deepin-overlay#2]
emerge: there are no ebuilds to satisfy "app-admin/system-config-printer-gnome".
(dependency required by "dde-base/dss-module-printer-1.20130703102957::necromancy" [ebuild])
(dependency required by "dde-base/dss-modules-meta-1.20130703102957::necromancy" [ebuild])
(dependency required by "dde-base/dde-meta-0.1::necromancy" [ebuild])
(dependency required by "dde-base/dde-meta" [argument])

**Comment by zhtengw** [comment]
Hi @jon, thanks for your reports. Actually, the ebuilds in this repo are written three years ago, and are very outdated now. Since mid 2015, Deepin develope and release new DDE which is written with GO language. And I don't have enough time to rewrite all ebuilds then. I just finished very few ebuilds.of all the packages needed. So I have not pushed the changes to this repo. 
If you are interested in the DDE for Gentoo, you are welcome to participate this small project.

**Comment by psykotik1** [comment]
maybe you could publish some of the ebuilds you've written to give me an idea of how to write them?

**Comment by zhtengw** [comment]
Hi, @psykotik1, I have pushed some new ebuilds. You can checkout the 2015 branch and view the recent commits. And I will open issues in https://github.com/linuxdeepin/developer-center/ when I meet any problems while porting.

**Comment by zhtengw** [comment]
Hi, @psykotik1 , I have just finished some key packages of DDE. And a preview version of DDE can run. You can update the deepin-overlay and emerge dde-meta for a test. If you meet any problems, please open an issues on this repo.

**Comment by zhtengw** [comment]
Hi @psykotik1 , porting DDE to gentoo is almost finished. If you are still using gentoo linux and insterested in DDE, run the command below to install:
```bash
layman -L && layman -a deepin
emerge --ask dde-meta
```
