### ISSUE TITLE
deepen-anything installing to incorrect libdir?

### ISSUE THREAD

**Issue by steev** [zhtengw/deepin-overlay#43]
I've recently updated my system, and when I install deepin-anything, it seems to throw the files into...

/usr/lib64/x86_64-linux-gnu - which seems to be a debian-ism

This is likely because I have dpkg installed on my system, so it actually resolves the 
```DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)```
line in the Makefile.  So we end up with the Makefile looking like:

```
mkdir -p $(DESTDIR)/usr/lib64/$(DEB_HOST_MULTIARCH)
```

Which because of having dpkg installed on my system, ends up spitting out `mkdir -p /usr/lib64/x86_64-linux-gnu`

I've added a workaround locally of adding

```
	sed -i "s|^DEB_HOST_MULTIARCH.*||g" Makefile
```
into the src_prepare - to get rid of the deb_host_multiarch definition, I'd send a pull request but my fork is woefully out of date at the moment.

**Comment by zhtengw** [comment]
OK, wait for your tested PR. I have not installed dpkg, so that I haven’t noticed this issue.------------------ Original ------------------From: Steev Klimaszewski  <notifications@github.com>Date: 周六,8月 4,2018 05:36To: zhtengw/deepin-overlay <deepin-overlay@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [zhtengw/deepin-overlay] deepen-anything installing to incorrectlibdir? (#43)I've recently updated my system, and when I install deepin-anything, it seems to throw the files into...
/usr/lib64/x86_64-linux-gnu - which seems to be a debian-ism
This is likely because I have dpkg installed on my system, so it actually resolves the
DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
line in the Makefile.  So we end up with the Makefile looking like:
mkdir -p $(DESTDIR)/usr/lib64/$(DEB_HOST_MULTIARCH)

Which because of having dpkg installed on my system, ends up spitting out mkdir -p /usr/lib64/x86_64-linux-gnu
I've added a workaround locally of adding
	sed -i "s|^DEB_HOST_MULTIARCH.*||g" Makefile

into the src_prepare - to get rid of the deb_host_multiarch definition, I'd send a pull request but my fork is woefully out of date at the moment.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zhtengw/deepin-overlay","title":"zhtengw/deepin-overlay","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/zhtengw/deepin-overlay"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"deepen-anything installing to incorrect libdir? (#43)"}],"action":{"name":"View Issue","url":"https://github.com/zhtengw/deepin-overlay/issues/43"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zhtengw/deepin-overlay/issues/43",
"url": "https://github.com/zhtengw/deepin-overlay/issues/43",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "deepen-anything installing to incorrect libdir? (#43)",
"sections": [
{
"text": "",
"activityTitle": "**Steev Klimaszewski**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@steev",
"facts": [
{
"name": "Repository: ",
"value": "zhtengw/deepin-overlay"
},
{
"name": "Issue #: ",
"value": 43
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"zhtengw/deepin-overlay\",\n\"issueId\": 43,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"zhtengw/deepin-overlay\",\n\"issueId\": 43\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/zhtengw/deepin-overlay/issues/43"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364549896\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by steev** [comment]
I've sent one - this allows me to install everything, but I seem to only get segfaults with dde-dock, dde-desktop, and dde-launcher.  I haven't tracked those down just yet.

**Comment by steev** [comment]
Closing since the issue was fixed, and segfaults are a separate issue.
